services:
  analysis:
    image: tanav2202/loan-eligibility:latest
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64
    command: bash -c "pip install python-json-logger>=2.0.0 && start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    environment:
      - JUPYTER_ENABLE_LAB=yes