services:
  analysis:
    image: tanav2202/loan-eligibility:v4.0.0
    build: .
    container_name: loan-analysis
    platform: linux/amd64
    ports:
      - "8000:8000"
    volumes:
      - .:/home/jovyan/work
    working_dir: /home/jovyan/work
    deploy:
      resources:
        limits:
          memory: 5G
    environment:
      - JUPYTER_ENABLE_LAB=yes