name: 'loan-analysis'
channels:
  - conda-forge
  # - defaults
dependencies:
  - python>=3.11,<3.13  
  - pip=25.3
  - ipykernel=7.1.0
  - nb_conda_kernels=2.5.1
  - altair=5.4.* 
  - vega_datasets=0.9.0
  - scipy=1.16.3
  - matplotlib>=3.2.2
  - scikit-learn=1.7.2
  - requests>=2.24.0
  - graphviz=14.0.4
  - python-graphviz=0.21
  # - eli5
  # - shap>=0.45 
  - jinja2=3.1.6
  - lightgbm=4.6.0
  - spacy=3.8.11
  - xgboost=3.1.2
  # - catboost
  - nltk=3.9.2
  - kaggle=1.8.0
  - imbalanced-learn=0.14.0
  - conda
  - mamba
  # - pip:
  #   - mglearn
  #   - spacymoji
  #   - altair_ally>=0.1.1  
